language: objeective-c
xcode_project: BTabViewController.xcodeproj # path to your xcodeproj folder
xcode_scheme: BTabViewControllerTests

osx_image: xcode11.6
env:
  matrix:
    - TEST_SDK=iphonesimulator13.6 OS=12.0 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator13.6 OS=12.0 NAME='iPhone 8'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project BTabViewController.xcodeproj -scheme BTabViewControllerTests -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 288ff82f-a5a2-470f-94d5-90afdfcd2889