language: objeective-c

osx_image: xcode11.5
env:
  matrix:
    - TEST_SDK=iphonesimulator13.3 OS=13.3 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator13.3 OS=13.3 NAME='iPhone 8'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project BTabViewController.xcodeproj -scheme BTabViewController -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 288ff82f-a5a2-470f-94d5-90afdfcd2889